<?php

function custom_mod_form_alter(&$form, &$form_state, $form_id) 
{
	switch($form_id) 
	{
		case 'comment_node_werk_form':
			$form['author']['homepage']['#access'] = FALSE;
			$form['comment_body']['und'][0]['value']['#title'] = t('Your story');
			$form['subject']['#size'] = 44;
			break;
	}
}

function custom_mod_html_head_alter(&$head_elements) 
{
	$path = request_path();
	$pathParts = explode('/', $path);
	global $base_url;
	
	if($pathParts[0] == 'comment' && $pathParts[1] != 'reply')
	{
		$commentObj = comment_load($pathParts[1], $reset = FALSE);	
	
		if(isset($commentObj))
		{
			$node = node_load($commentObj->nid);
			
			$head_elements['metatag_canonical']['#value'] = $base_url.'/'.$path;
			
			//metatags
			//$head_elements['metatag_og:title_0']['#value'] = $commentObj->subject;
			$head_elements['metatag_description_0']['#value'] = $commentObj->comment_body[LANGUAGE_NONE][0]['value'];
			
			//dublin core
			$head_elements['metatag_dcterms.title_0']['#value'] = $commentObj->subject;
			$head_elements['metatag_dcterms.description_0']['#value'] = $commentObj->comment_body[LANGUAGE_NONE][0]['value'];
			//URL
			$head_elements['metatag_dcterms.identifier_0']['#value'] = $base_url.'/'.$path;
			
			//google +
			//title
			$head_elements['metatag_itemprop:name_0']['#value'] = $commentObj->subject;
			$head_elements['metatag_itemprop:description_0']['#value'] = $commentObj->comment_body[LANGUAGE_NONE][0]['value'];
			
			//twitter
			$head_elements['metatag_twitter:title_0']['#value'] = $commentObj->subject;
			$head_elements['metatag_twitter:description_0']['#value'] = $commentObj->comment_body[LANGUAGE_NONE][0]['value'];
			$head_elements['metatag_twitter:url_0']['#value'] = $base_url.'/'.$path;
			$head_elements['metatag_twitter:image:src_0']['#value'] = file_create_url($node->field_image[LANGUAGE_NONE]['0']['uri']);
			
			//OpenGraph
			$head_elements['metatag_og:title_0']['#value'] = $commentObj->subject;
			$head_elements['metatag_og:description_0']['#value'] = $commentObj->comment_body[LANGUAGE_NONE][0]['value'];
			$head_elements['metatag_og:image_0']['#value'] = file_create_url($node->field_image[LANGUAGE_NONE]['0']['uri']);
			$head_elements['metatag_og:url_0']['#value'] = $base_url.'/'.$path;
		}
	}
}

function custom_mod_node_view_alter(&$build)
{
	if(isset($build['links']['comment']['#links']['comment-add']))
	{
		if(isset($build['links']['comment']['#links']['comment-comments']['title']))
		{
			$titleCount = explode(' ', $build['links']['comment']['#links']['comment-comments']['title']);
			if(is_numeric($titleCount[0]))
			{
				$titleCount[1] = t('Story');
					
				if($titleCount[0] > 1)
				{
					$titleCount[1] = t('Storys');
				}
				$titleCount[0] = '<span class="comment_count">' . $titleCount[0] . '</span>';
			}
			
			$glue = '';
			$build['links']['comment']['#links']['comment-comments']['title'] = implode($glue, $titleCount);
		}

		
		$build['links']['comment']['#links']['comment-comments']['attributes']['title'] = t('Read first story');
		$build['links']['comment']['#links']['comment-add']['title'] = t('Tell your Story');
		$build['links']['comment']['#links']['comment-add']['attributes']['title'] = t('Tell new story');
		
	}
}
?>