<?php

function custom_mod_form_alter(&$form, &$form_state, $form_id) 
{
	switch($form_id) 
	{
		case 'comment_node_werk_form':
			$form['author']['homepage']['#access'] = FALSE;
			$form['comment_body']['und'][0]['value']['#title'] = t('Your story');
			break;
	}
}

function custom_mod_node_view_alter(&$build)
{
	if(isset($build['links']['comment']['#links']['comment-add']))
	{
		if(isset($build['links']['comment']['#links']['comment-comments']['title']))
		{
			$titleCount = explode(' ', $build['links']['comment']['#links']['comment-comments']['title']);
			if(is_numeric($titleCount[0]))
			{
				$titleCount[1] = t('Story');
					
				if($titleCount[0] > 1)
				{
					$titleCount[1] = t('Storys');
				}
				$titleCount[0] = '<span class="comment_count">' . $titleCount[0] . '</span>';
			}
			
			$glue = '';
			$build['links']['comment']['#links']['comment-comments']['title'] = implode($glue, $titleCount);
		}

		
		$build['links']['comment']['#links']['comment-comments']['attributes']['title'] = t('Read first story');
		$build['links']['comment']['#links']['comment-add']['title'] = t('Tell your Story');
		$build['links']['comment']['#links']['comment-add']['attributes']['title'] = t('Tell new story');
		
	}
}